// Generated by gencpp from file vision/custMsg.msg
// DO NOT EDIT!


#ifndef VISION_MESSAGE_CUSTMSG_H
#define VISION_MESSAGE_CUSTMSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace vision
{
template <class ContainerAllocator>
struct custMsg_
{
  typedef custMsg_<ContainerAllocator> Type;

  custMsg_()
    : index(0)
    , x(0.0)
    , y(0.0)
    , z(0.0)  {
    }
  custMsg_(const ContainerAllocator& _alloc)
    : index(0)
    , x(0.0)
    , y(0.0)
    , z(0.0)  {
  (void)_alloc;
    }



   typedef int32_t _index_type;
  _index_type index;

   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _z_type;
  _z_type z;





  typedef boost::shared_ptr< ::vision::custMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vision::custMsg_<ContainerAllocator> const> ConstPtr;

}; // struct custMsg_

typedef ::vision::custMsg_<std::allocator<void> > custMsg;

typedef boost::shared_ptr< ::vision::custMsg > custMsgPtr;
typedef boost::shared_ptr< ::vision::custMsg const> custMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vision::custMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vision::custMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::vision::custMsg_<ContainerAllocator1> & lhs, const ::vision::custMsg_<ContainerAllocator2> & rhs)
{
  return lhs.index == rhs.index &&
    lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::vision::custMsg_<ContainerAllocator1> & lhs, const ::vision::custMsg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace vision

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::vision::custMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vision::custMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vision::custMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vision::custMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vision::custMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vision::custMsg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vision::custMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2622e279f148bab2f2656b233b9ab6cd";
  }

  static const char* value(const ::vision::custMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2622e279f148bab2ULL;
  static const uint64_t static_value2 = 0xf2656b233b9ab6cdULL;
};

template<class ContainerAllocator>
struct DataType< ::vision::custMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vision/custMsg";
  }

  static const char* value(const ::vision::custMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vision::custMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 index\n"
"float32 x\n"
"float32 y\n"
"float32 z\n"
;
  }

  static const char* value(const ::vision::custMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vision::custMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.index);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct custMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vision::custMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vision::custMsg_<ContainerAllocator>& v)
  {
    s << indent << "index: ";
    Printer<int32_t>::stream(s, indent + "  ", v.index);
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<float>::stream(s, indent + "  ", v.z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VISION_MESSAGE_CUSTMSG_H
